export const TABS = {
  ThongTinChung: 'Thông tin chung',
  XetLenLopHocBong: 'Xét lên lớp - Học bổng',
};

export const FORM_DEFAULT_VALUES = {
  idQuyCheHocVu: '',
  soTinhChiNoToiHT: null,
  isRangBuocDKT: false,
  heSoDiemLT: null,
  heSoDiemTH: null,
  isTinhTheoDiemLT: false,
  isSoCotDiemKTTK: false,
  soCotDiemKTTK: null,

  dddS_DiemThuongKy: null,
  dddS_DiemTBMon: null,
  dddS_DiemTBChung: null,
  dddS_DiemTKMon: null,
  dddS_DiemTBHK: null,

  dkdT_DaDongHP: false,
  dkdT_IsDiemTBThuongKy: false,
  dkdT_DiemTBThuongKy: null,
  dkdT_IsDiemTBThuongXuyen: false,
  dkdT_DiemTBThuongXuyen: null,
  dkdT_IsDiemGiuaKy: false,
  dkdT_DiemGiuaKy: null,
  dkdT_IsDiemTieuLuan: false,
  dkdT_DiemTieuLuan: null,
  dkdT_IsKhongVangQua: false,
  dkdT_PTTongVang: null,
  dkdT_PTLyThuyet: null,
  dkdT_PTThucHanh: null,

  dktH_DiemThoiHocMoiHK: null,
  dktH_SoHKCanhBaoMax: null,
  dktH_DiemHKDau: null,
  dktH_DiemHKLienTiep: null,
  dktH_HKLienTiep: null,
  dktH_DiemHKTiepTheo: null,
  dktH_IsXetTamNgung: false,
  dktH_XetTamNgungTu: null,
  dktH_XetTamNgungDen: null,
  dktH_SoTNDiemF: null,
  dktH_IsKiemTraNoHP: false,
  dktH_IsSoLanVP: false,
  dktH_SoLanVP: null,
  dktH_IdMucDoVP: '',
  dktH_MucDoVP: null,
  dktH_IsShowGCMonHocRot: false,
  dktH_IsShowGCMonHocKhac: false,

  hbxL_IsThangDiem1null: false,
  hbxL_IsDiemHaBacTu: false,
  hbxL_DiemHaBacTu: null,
  hbxL_IsSoLanVPKL: false,
  hbxL_SoLanVPKL: null,
  hbxL_IdMucDoVPKL: '',
  hbxL_MucDoVPKL: null,
  hbxL_IsSoLanVPQC: false,
  hbxL_SoLanVPQC: null,
  hbxL_IdMucDoVPQC: '',
  hbxL_MucDoVPQC: undefined,
  hbxL_IsSoMonTLHL: false,
  hbxL_SoMonTLHL: null,
  hbxL_IsTLHLChiLayMonTBC: false,
  hbxL_IsTLHLChiLauMonCTK: false,

  dH_DiemTB: null,
  dh_DiemHK: null,
  dh_SoTCDangKy: null,

  hB_DiemTrungBinh: null,
  hB_DiemTBToiThieu: null,
  hB_SoTCDangKy: null,
  hB_SoTCDKNam: null,
};
