import type { GridAlignment, GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { dateCellFormat } from '@renderer/shared/utils/date';

export const thongKeInBieuMauColumns = generateTableConfigs([
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    minWidth: 130,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.sinhVien?.maSinhVien ?? '',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    minWidth: 160,
    flex: 1.2,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.sinhVien?.hoDem ?? '',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.sinhVien?.ten ?? '',
  },
  {
    field: 'gioiTinh',
    headerName: 'Giới tính',
    minWidth: 110,
    flex: 0.8,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => (row.sinhVien?.gioiTinh == 0 ? 'Nữ' : 'Nam'),
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.sinhVien?.ngaySinh),
  },
  {
    field: 'tenLop',
    headerName: 'Tên lớp',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.sinhVien?.lopHoc?.tenLop || '',
  },
  {
    field: 'maBieuMau',
    headerName: 'Mã biểu mẫu',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.bieuMau?.maBieuMau || '',
  },
  {
    field: 'tenBieuMau',
    headerName: 'Tên biểu mẫu',
    minWidth: 180,
    flex: 1.4,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.bieuMau?.tenBieuMau || '',
  },
  {
    field: 'mayIn',
    headerName: 'Máy in',
    minWidth: 160,
    flex: 1.2,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ngayIn',
    headerName: 'Ngày in',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngayIn),
  },
  {
    field: 'nguoiIn',
    headerName: 'Người in',
    minWidth: 160,
    flex: 1.2,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) =>
      `${row.nguoiIn?.ho ?? ''} ${row.nguoiIn?.tenDem ?? ''} ${row.nguoiIn?.ten ?? ''}`,
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    minWidth: 180,
    flex: 1.2,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
]) as GridColDef[];
