import type { GridAlignment, GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { TRANG_THAI_SV_MAP } from '@renderer/shared/constants';
import { dateCellFormat } from '@renderer/shared/utils/date';

export const hoSoTuyenSinhColumns = generateTableConfigs([
  {
    field: 'maHoSo',
    headerName: 'Mã hồ sơ',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soBaoDanh',
    headerName: 'Số báo danh',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'thuTuNhanHoSo',
    headerName: 'Thứ tự nhận hồ sơ',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    minWidth: 130,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maBarcode',
    headerName: 'Mã barcode',
    minWidth: 130,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ten',
    headerName: 'Tên',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'gioiTinh',
    headerName: 'Giới tính',
    minWidth: 110,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => (row?.gioiTinh == 0 ? 'Nam' : 'Nữ'),
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngaySinh),
  },
  {
    field: 'donViCuDiHoc',
    headerName: 'Đơn vị cư trú đi học',
    minWidth: 200,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'danToc',
    headerName: 'Dân tộc',
    minWidth: 130,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.danToc?.ten ?? '',
  },
  {
    field: 'tonGiao',
    headerName: 'Tôn giáo',
    minWidth: 130,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.tonGiao?.ten ?? '',
  },
  {
    field: 'hoKhauThuongTru',
    headerName: 'Hộ khẩu thường trú',
    minWidth: 220,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'hoKhauTamTru',
    headerName: 'Hộ khẩu tạm trú',
    minWidth: 220,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'diaChiLienLac',
    headerName: 'Địa chỉ liên lạc',
    minWidth: 220,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tenTinh',
    headerName: 'Tên tỉnh',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.tenTinh?.ten ?? '',
  },
  {
    field: 'tenHuyen',
    headerName: 'Tên huyện',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.tenHuyen?.ten ?? '',
  },
  {
    field: 'tenPhuongXa',
    headerName: 'Tên phường xã',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.tenPhuongXa?.ten ?? '',
  },
  {
    field: 'noiSinhTinh',
    headerName: 'Nơi sinh Tỉnh',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.noiSinhTinh?.ten ?? '',
  },
  {
    field: 'noiSinhHuyen',
    headerName: 'Nơi sinh Huyện',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.noiSinhHuyen?.ten ?? '',
  },
  {
    field: 'noiSinhPhuongXa',
    headerName: 'Nơi sinh Phường xã',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.noiSinhPhuongXa?.ten ?? '',
  },
  {
    field: 'lopHoc',
    headerName: 'Lớp học',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.lopHoc?.tenLopHoc ?? '',
  },
  {
    field: 'loaiSinhVien',
    headerName: 'Loại sinh viên',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.loaiSinhVien?.tenLoaiSinhVien ?? '',
  },
  {
    field: 'nguyenQuan',
    headerName: 'Nguyên quán',
    minWidth: 200,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'doiTuongUuTien',
    headerName: 'Tên đối tượng',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.doiTuongUuTien?.ten ?? '',
  },
  {
    field: 'doiTuongChinhSach',
    headerName: 'Tên đối tượng chính sách',
    minWidth: 220,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.doiTuongChinhSach?.ten ?? '',
  },
  {
    field: 'khuVuc',
    headerName: 'Khu vực',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'phanHe',
    headerName: 'Phân hệ',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'truongTotNghiep',
    headerName: 'Trường tốt nghiệp',
    minWidth: 200,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ngayVaoDoan',
    headerName: 'Ngày vào đoàn',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngayVaoDoan),
  },
  {
    field: 'ngayVaoDang',
    headerName: 'Ngày vào đảng',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngayVaoDang),
  },
  {
    field: 'soCMND',
    headerName: 'Số CMND',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ngayCap',
    headerName: 'Ngày cấp',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngayCap),
  },
  {
    field: 'noiCapCMND',
    headerName: 'Nơi cấp CMND',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'coSoDaoTao',
    headerName: 'Cơ sở',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.coSoDaoTao?.tenCoSo ?? '',
  },
  {
    field: 'khoaHoc',
    headerName: 'Khóa học',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.khoaHoc?.tenKhoaHoc ?? '',
  },
  {
    field: 'bacDaoTao',
    headerName: 'Bậc đào tạo',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.bacDaoTao?.tenBacDaoTao ?? '',
  },
  {
    field: 'loaiDaoTao',
    headerName: 'Loại đào tạo',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.loaiDaoTao?.tenLoaiDaoTao ?? '',
  },
  {
    field: 'nganh',
    headerName: 'Ngành',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.nganh?.tenNganh ?? '',
  },
  {
    field: 'chuyenNganh',
    headerName: 'Chuyên ngành',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.chuyenNganh?.tenChuyenNganh ?? '',
  },
  {
    field: 'nganh2',
    headerName: 'Ngành 2',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.nganh2?.tenNganh ?? '',
  },
  {
    field: 'ngayNhapHoc',
    headerName: 'Ngày nhập học',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngayNhapHoc),
  },
  {
    field: 'hoTenCha',
    headerName: 'Họ tên cha',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ngheNghiepCha',
    headerName: 'Nghề nghiệp cha',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'hoTenMe',
    headerName: 'Họ tên mẹ',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ngheNghiepMe',
    headerName: 'Nghề nghiệp mẹ',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soDienThoai',
    headerName: 'Điện thoại',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soDienThoaiPhuHuynh',
    headerName: 'Điện thoại phụ huynh',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soDienThoai2',
    headerName: 'Điện thoại 2',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soDienThoai3',
    headerName: 'Điện thoại 3',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'email',
    headerName: 'Email',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'emailTruong',
    headerName: 'Mail trường',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTaiKhoan',
    headerName: 'Số tài khoản',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tenTaiKhoan',
    headerName: 'Tên tài khoản',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tenNganHang',
    headerName: 'Tên ngân hàng',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'chiNhanhNganHang',
    headerName: 'Chi nhánh ngân hàng',
    minWidth: 210,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maBHXHBHYT',
    headerName: 'Mã BHXH/BHYT',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'trangThai',
    headerName: 'Trạng thái',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => {
      const value = row?.trangThai?.toString();
      return TRANG_THAI_SV_MAP[value] ?? '';
    },
  },
  {
    field: 'quocTich',
    headerName: 'Quốc tịch',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.quocTich?.ten ?? '',
  },
  {
    field: 'truongLop12',
    headerName: 'Trường lớp 12',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soQuyetDinh',
    headerName: 'Số quyết định',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ngayQuyetDinh',
    headerName: 'Ngày ra quyết định',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngayQuyetDinh),
  },
  {
    field: 'dotRaQuyetDinh',
    headerName: 'Đợt ra quyết định',
    minWidth: 170,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'chucVu',
    headerName: 'Chức vụ',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'donViCongTac',
    headerName: 'Đơn vị công tác',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    minWidth: 200,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
]) as GridColDef[];
