import { QuyUocCotDiemLopHocPhan } from '@renderer/shared/types';

export const mockData: QuyUocCotDiemLopHocPhan[] = [
  {
    id: '1',
    maMonHoc: 'CS101',
    tenMonHoc: 'Nhập môn Lập trình',
    maLHP: 'LHP001',
    maLopBanDau: 'LPD001',
    soTC: '3',
    LT: true,
    soTietLT: 30,
    soTietTH: 15,
    quyUocCotDiem: 'A,B,C,D,F',
    khoaDiemQT: false,
    khoaDiemKT: false,
    heDaoTao: 'Đại học chính quy',
  },
  {
    id: '2',
    maMonHoc: 'MA202',
    tenMonHoc: 'Giải tích 2',
    maLHP: 'LHP002',
    maLopBanDau: 'LPD002',
    soTC: '4',
    LT: true,
    soTietLT: 45,
    soTietTH: 0,
    quyUocCotDiem: 'A+,A,B+,B,C+,C,D,F',
    khoaDiemQT: true,
    khoaDiemKT: false,
    heDaoTao: 'Đại học chính quy',
  },
  {
    id: '3',
    maMonHoc: 'PH103',
    tenMonHoc: 'Vật lý đại cương',
    maLHP: 'LHP003',
    maLopBanDau: 'LPD003',
    soTC: '3',
    LT: false,
    soTietLT: 15,
    soTietTH: 30,
    quyUocCotDiem: '10-point',
    khoaDiemQT: false,
    khoaDiemKT: true,
    heDaoTao: 'Cao đẳng',
  },
  {
    id: '4',
    maMonHoc: 'ENG101',
    tenMonHoc: 'Tiếng Anh cơ bản',
    maLHP: 'LHP004',
    maLopBanDau: 'LPD004',
    soTC: '2',
    LT: true,
    soTietLT: 20,
    soTietTH: 10,
    quyUocCotDiem: 'Pass/Fail',
    khoaDiemQT: true,
    khoaDiemKT: true,
    heDaoTao: 'Liên thông',
  },
];
