import { GridColDef } from '@mui/x-data-grid';

export const chuyenLopHocPhanColumns: GridColDef[] = [
  {
    field: 'index',
    headerName: '*',
    width: 50,
    sortable: true,
    align: 'center' as const,
    headerAlign: 'center' as const,
  },
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    flex: 1,
    minWidth: 120,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    flex: 1,
    minWidth: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'gioiTinh',
    headerName: 'Giới tính',
    width: 110,
    type: 'singleSelect',
    valueOptions: ['Nam', 'Nữ', 'Khác'],
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    flex: 1,
    minWidth: 130,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenLop',
    headerName: 'Tên lớp',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayDangKy',
    headerName: 'Ngày đăng ký',
    flex: 1,
    minWidth: 140,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'trangThai',
    headerName: 'Trạng thái',
    flex: 1,
    minWidth: 140,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'nhomLopDanhNghia',
    headerName: 'Nhóm lớp danh nghĩa',
    flex: 1,
    minWidth: 160,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'nhomTH',
    headerName: 'Nhóm TH',
    flex: 1,
    minWidth: 120,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'diemSo',
    headerName: 'Điểm số',
    flex: 1,
    minWidth: 120,
    type: 'number',
    align: 'center',
    headerAlign: 'center',
  },
];
