import { GridColDef } from '@mui/x-data-grid';

export const baoCaoSinhVienKhongDangKyHocPhanTheoDotColumns: GridColDef[] = [
  {
    field: 'index',
    headerName: '*',
    width: 50,
    sortable: true,
    align: 'center' as const,
    headerAlign: 'center' as const,
  },
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    flex: 1,
    minWidth: 120,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    flex: 1,
    minWidth: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'gioiTinh',
    headerName: 'Giới tính',
    width: 110,
    type: 'singleSelect',
    valueOptions: ['Nam', 'Nữ', 'Khác'],
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    flex: 1,
    minWidth: 130,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soDienThoai',
    headerName: 'Số điện thoại',
    flex: 1,
    minWidth: 130,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'lopHoc',
    headerName: 'Lớp học',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'maHocPhan',
    headerName: 'Mã học phần',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenHocPhan',
    headerName: 'Tên học phần',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'trangThai',
    headerName: 'Trạng thái',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
];

