import { GridAlignment, GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';

export const TieuChuanXetHocBongColumns: GridColDef[] = generateTableConfigs([
  {
    field: 'stt',
    headerName: 'STT',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLucDiem10Tu',
    headerName: 'Học lực 10 từ',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLucDiem10Den',
    headerName: 'Học lực 10 đến',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hanhKiemTu',
    headerName: 'Hạnh kiểm từ',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hanhKiemDen',
    headerName: 'Hạnh kiểm đến',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  { field: 'ghiChu', headerName: 'Ghi chú', flex: 1, minWidth: 200 },
  {
    field: 'nhom',
    headerName: 'Nhóm',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocBong',
    headerName: 'Học bổng',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLucDiem4Tu',
    headerName: 'Học lực 4 từ',
    minWidth: 140,
    flex: 1,
    sortable: true,
    type: 'number',
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLucDiem4Den',
    headerName: 'Học lực 4 đến',
    minWidth: 150,
    flex: 1,
    sortable: true,
    type: 'number',
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'soTien',
    headerName: 'Số tiền',
    minWidth: 140,
    flex: 1,
    sortable: true,
    type: 'number',
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'phanTramSoTien',
    headerName: 'Phần trăm số tiền (%)',
    minWidth: 180,
    flex: 1,
    sortable: true,
    type: 'number',
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
]);
