import { GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { KhenThuong, LoaiKhenThuong } from '@renderer/shared/types';

export const quyCheRenLuyenKhenThuongColumns: GridColDef<KhenThuong>[] = generateTableConfigs([
  {
    field: 'loaiKhenThuong',
    headerName: 'Loại khen thưởng',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
    valueGetter: (value: LoaiKhenThuong) => value?.tenLoaiKhenThuong,
  },
  {
    field: 'maKhenThuong',
    headerName: 'Mã khen thưởng',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'tenKhenThuong',
    headerName: 'Tên khen thưởng',
    flex: 1,
    minWidth: 180,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'diemCong',
    headerName: 'Điểm cộng',
    flex: 1,
    minWidth: 120,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'diemCongToiDa',
    headerName: 'Điểm cộng tối đa',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'noiDung',
    headerName: 'Nội dung',
    flex: 2,
    minWidth: 200,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'isViPhamNoiTru',
    headerName: 'Vi phạm nội trú',
    flex: 1,
    minWidth: 160,
    type: 'boolean',
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    flex: 1,
    minWidth: 180,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
]);
