import { GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { BacDaoTao, LoaiDaoTao } from '@renderer/shared/types';

type KhoiNganh = { id: string; tenKhoiNganh: string };

export const thoiGianDaoTaoColumns: GridColDef[] = generateTableConfigs([
  {
    field: 'bacDaoTao',
    headerName: 'Bậc đào tạo',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: BacDaoTao) => value.tenBacDaoTao || '',
  },
  {
    field: 'loaiDaoTao',
    headerName: 'Loại đào tạo',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: LoaiDaoTao) => value.tenLoaiDaoTao || '',
  },
  {
    field: 'khoiNganh',
    headerName: 'Khối ngành',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: KhoiNganh) => (value ? value.tenKhoiNganh : ''),
  },
  {
    field: 'thoiGianKeHoach',
    headerName: 'Thời gian kế hoạch',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
  },
  {
    field: 'thoiGianToiThieu',
    headerName: 'Thời gian tối thiểu',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
  },
  {
    field: 'thoiGianToiDa',
    headerName: 'Thời gian tối đa',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
  },
  {
    field: 'hanCheDKHP',
    headerName: 'Hạn chế DKHP',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'giayBaoTrungTuyen',
    headerName: 'Giấy báo trúng tuyển',
    flex: 1,
    minWidth: 200,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'bangTotNghiep',
    headerName: 'Bằng tốt nghiệp',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenBang_BangDiem ?? '',
  },
  {
    field: 'heSoDaoTao',
    headerName: 'Hệ số đào tạo',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
  },
  {
    field: 'kyTuMaSV',
    headerName: 'Ký tự mã sinh viên',
    flex: 1,
    minWidth: 180,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
]);
