import { GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { format } from 'date-fns';

export const hocKyColumns: GridColDef[] = generateTableConfigs([
  {
    field: 'tenDot',
    headerName: 'Tên đợt',
    flex: 2,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soThuTu',
    headerName: 'Số thứ tự',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'soTuan',
    headerName: 'Số tuần',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'heSo',
    headerName: 'Hệ số',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'isActive',
    headerName: 'Kích hoạt',
    type: 'boolean',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'isDKHP',
    headerName: 'ĐKHP',
    type: 'boolean',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'isDKNTTT',
    headerName: 'ĐKNTTT',
    type: 'boolean',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'isVisible',
    headerName: 'Hiển thị',
    type: 'boolean',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'tuThang',
    headerName: 'Từ tháng',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'denThang',
    headerName: 'Đến tháng',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tuNgay',
    headerName: 'Từ ngày',
    flex: 1,
    minWidth: 150,
    valueGetter: (value: Date) => format(value, 'dd/MM/yyyy'),
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'denNgay',
    headerName: 'Đến ngày',
    flex: 1,
    minWidth: 150,
    valueGetter: (value: Date) => format(value, 'dd/MM/yyyy'),
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenDayDu',
    headerName: 'Tên đầy đủ',
    flex: 2,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenTiengAnh',
    headerName: 'Tên tiếng Anh',
    flex: 2,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'namHanhChinh',
    headerName: 'Năm HC',
    flex: 1.5,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    flex: 2,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150,
  },
]);
