import { GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';

export const danhMucBacDaoTaoColumns: GridColDef[] = generateTableConfigs([
  {
    field: 'maBacDaoTao',
    headerName: 'Mã Bậc Đào Tạo',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenBacDaoTao',
    headerName: 'Tên Bậc Đào Tạo',
    flex: 1,
    minWidth: 220,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenTiengAnh',
    headerName: 'Tên Tiếng Anh',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hinhThucDaoTao',
    headerName: 'Hình Thức Đào Tạo',
    flex: 1,
    minWidth: 220,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'stt',
    headerName: 'STT',
    width: 100,
    type: 'number',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi Chú',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenLoaiBangCapTN',
    headerName: 'Loại Bằng Cấp TN',
    flex: 1,
    minWidth: 220,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenLoaiBangCapTN_ENG',
    headerName: 'Tên Loại Bằng Cấp TN (Tiếng Anh)',
    flex: 1,
    minWidth: 250,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'isVisible',
    headerName: 'Hiển Thị',
    width: 120,
    type: 'boolean',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'phongBanKyBM',
    headerName: 'Phòng ban ký BM',
    width: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  // {
  //   field: 'daoTaoMonVanHoa',
  //   headerName: 'Đào Tạo Môn Văn Hóa',
  //   flex: 1,
  //   minWidth: 220,
  //   type: 'string',
  //   align: 'center',
  //   headerAlign: 'center',
  // },
  // {
  //   field: 'kyTuMaSinhVien',
  //   headerName: 'Ký Tự Mã Sinh Viên',
  //   minWidth: 220,
  //   type: 'string',
  //   align: 'center',
  //   headerAlign: 'center',
  // },
  // {
  //   field: 'kyTuMaHoSoTuyenSinh',
  //   headerName: 'Ký Tự Mã Hồ Sơ Tuyển Sinh',
  //   minWidth: 260,
  //   type: 'string',
  //   align: 'center',
  //   headerAlign: 'center',
  // },
]);
