import { GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { HanhViViPham, LoaiHanhViViPham } from '@renderer/shared/types';

export const quyCheRenLuyenViPhamColumns: GridColDef<HanhViViPham>[] = generateTableConfigs([
  {
    field: 'loaiHanhVi',
    headerName: 'Loại hành vi vi phạm',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
    valueGetter: (value: LoaiHanhViViPham) => value.tenLoaiHanhVi,
  },
  {
    field: 'maHanhVi',
    headerName: 'Mã hành vi',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'tenHanhVi',
    headerName: 'Tên hành vi',
    flex: 1,
    minWidth: 180,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'diemTru',
    headerName: 'Điểm trừ',
    flex: 1,
    minWidth: 120,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'diemTruToiDa',
    headerName: 'Điểm trừ tối đa  ',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'noiDung',
    headerName: 'Nội dung',
    flex: 2,
    minWidth: 200,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'isViPhamNoiTru',
    headerName: 'Vi phạm nội trú',
    flex: 1,
    minWidth: 160,
    type: 'boolean',
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'isKhongSuDung',
    headerName: 'Không sử dụng',
    flex: 1,
    minWidth: 150,
    type: 'boolean',
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'mucDo',
    headerName: 'Mức độ',
    flex: 1,
    minWidth: 120,
    type: 'number',
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    flex: 1,
    minWidth: 180,
    headerAlign: 'center',
    align: 'center',
    hideSortIcons: true,
    sortable: true,
  },
]);
