import { GridAlignment, GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { BacDaoTao, Khoa, KhoaHoc, LoaiDaoTao, NganhHoc } from '@renderer/shared/types';
import { format } from 'date-fns';

export const columns: GridColDef[] = generateTableConfigs([
  {
    field: 'maLop',
    headerName: 'Mã Lớp Học',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenLop',
    headerName: 'Tên Lớp Học',
    flex: 1,
    minWidth: 220,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenTiengAnh',
    headerName: 'Tên Tiếng Anh',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'siSoDuKien',
    headerName: 'Sỉ Số Dự Kiến',
    flex: 1,
    minWidth: 200,
    type: 'number',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'siSoHienTai',
    headerName: 'Sỉ Số Hiện Tại',
    flex: 1,
    minWidth: 200,
    type: 'number',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'siSoDangHoc',
    headerName: 'Sỉ số Đang Học',
    flex: 1,
    minWidth: 200,
    type: 'number',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'khoa',
    headerName: 'Khoa',
    sortable: true,
    width: 130,
    editable: false,
    valueGetter: (value: Khoa) => value?.tenKhoa,
  },
  {
    field: 'khoaHoc',
    headerName: 'Khoa Học',
    minWidth: 150,
    align: 'center' as GridAlignment,
    headerAlign: 'center' as GridAlignment,
    flex: 2,
    valueGetter: (value: KhoaHoc) => value?.tenKhoaHoc || '',
  },
  {
    field: 'bacDaoTao',
    headerName: 'Bậc đào tạo',
    minWidth: 150,
    align: 'center' as GridAlignment,
    headerAlign: 'center' as GridAlignment,
    flex: 2,
    valueGetter: (value: BacDaoTao) => value?.tenBacDaoTao || '',
  },
  {
    field: 'loaiDaoTao',
    headerName: 'Loại đào tạo',
    minWidth: 150,
    align: 'center' as GridAlignment,
    headerAlign: 'center' as GridAlignment,
    flex: 2,
    valueGetter: (value: LoaiDaoTao) => value?.tenLoaiDaoTao || '',
  },
  {
    field: 'caHoc',
    headerName: 'Ca học',
    minWidth: 150,
    align: 'center' as GridAlignment,
    headerAlign: 'center' as GridAlignment,
    flex: 2,
    valueGetter: (value: any) => value?.tenCaHoc || '',
  },
  {
    field: 'nganhHoc',
    headerName: 'Ngành',
    minWidth: 150,
    align: 'center' as GridAlignment,
    headerAlign: 'center' as GridAlignment,
    flex: 2,
    valueGetter: (value: NganhHoc) => value?.tenNganhHoc || '',
  },
  {
    field: 'giangVienChuNhiem',
    headerName: 'Giảng viêng chủ nhiệm',
    minWidth: 150,
    align: 'center' as GridAlignment,
    headerAlign: 'center' as GridAlignment,
    flex: 2,
    valueGetter: (value: any) => (value ? `${value?.hoDem} ${value?.ten}` : ''),
  },
  {
    field: 'coVanHocTap',
    headerName: 'Cố vấn học tập',
    minWidth: 150,
    align: 'center' as GridAlignment,
    headerAlign: 'center' as GridAlignment,
    flex: 2,
    valueGetter: (value: any) => (value ? `${value?.hoDem} ${value?.ten}` : ''),
  },
  {
    field: 'chuyenNganh',
    headerName: 'Chuyên Ngành',
    width: 120,
    valueGetter: (params: any) => params?.tenChuyenNganh,
  },
  {
    field: 'coSoDaoTao',
    headerName: 'Cơ Sở',
    width: 100,
    valueGetter: (params: any) => params?.tenCoSo,
  },
  {
    field: 'kyTuMSSV',
    headerName: 'Ký tự MSSV',
    flex: 1,
    minWidth: 150,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soHopDong',
    headerName: 'Số hợp đồng',
    flex: 1,
    minWidth: 150,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayHopDong',
    headerName: 'Số hợp đồng',
    flex: 1,
    minWidth: 150,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (params: any) => (params ? format(params, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'soQuyetDinhThanhLapLop',
    headerName: 'Số quyết định thành lập lớp',
    flex: 1,
    minWidth: 150,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayRaQuyetDinh',
    headerName: 'Số hợp đồng',
    flex: 1,
    minWidth: 150,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (params: any) => (params ? format(params, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi Chú',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'isVisible',
    headerName: 'Hiển Thị',
    width: 120,
    type: 'boolean',
    align: 'center',
    headerAlign: 'center',
  },
]);
