import { Checkbox } from '@mui/material';
import { GridAlignment, GridColDef, GridRenderCellParams } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { QuyUocCotDiem } from '@renderer/shared/types';

export const quyUocCotDiemColumns: GridColDef<QuyUocCotDiem>[] = generateTableConfigs([
  {
    field: 'tenQuyUoc',
    headerName: 'Quy ước',
    flex: 1,
    minWidth: 200,
    editable: true,
    sortable: true,
  },
  {
    field: 'quyChe_TinChi',
    headerName: 'Quy chế',
    flex: 1,
    minWidth: 180,
    editable: true,
    sortable: true,
    renderCell: (params) => params.value?.quyCheHocVu?.tenQuyChe,
  },
  {
    field: 'kieuMon',
    headerName: 'Kiểu môn',
    flex: 1,
    minWidth: 150,
    editable: true,
    sortable: true,
    renderCell: (params) => params.value?.tenKieuMonHoc
  },
  {
    field: 'isKhongTinhTBC',
    headerName: 'Không tính TBC',
    width: 100,
    renderCell: (params: GridRenderCellParams) => <Checkbox checked={params.value} disabled />,
    editable: true,
    type: 'boolean',
    sortable: true,
  },
  {
    field: 'diemTBC',
    headerName: 'Điểm đạt',
    width: 120,
    editable: true,
    type: 'number',
    sortable: true,
  },
  {
    field: 'isChiDiemCuoiKy',
    headerName: 'Chỉ điểm cuối kỳ',
    width: 100,
    renderCell: (params: GridRenderCellParams) => <Checkbox checked={params.value} disabled />,
    editable: true,
    type: 'boolean',
    sortable: true,
  },
  {
    field: 'isChiDanhGia',
    headerName: 'Chỉ đánh giá',
    width: 130,
    renderCell: (params: GridRenderCellParams) => <Checkbox checked={params.value} disabled />,
    editable: true,
    type: 'boolean',
    sortable: true,
  },
  {
    field: 'isXetDuThiGiuaKy',
    headerName: 'Xét dự thi giữa kỳ',
    width: 120,
    renderCell: (params: GridRenderCellParams) => <Checkbox checked={params.value} disabled />,
    editable: true,
    type: 'boolean',
    sortable: true,
  },
  {
    field: 'chuyenCan',
    headerName: 'Chuyên cần (%)',
    width: 120,
    editable: true,
    type: 'number',
    sortable: true,
  },
  {
    field: 'thuongXuyen1',
    headerName: '1',
    width: 40,
    editable: true,
    type: 'number',
    sortable: true,
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'thuongXuyen2',
    headerName: '2',
    width: 40,
    editable: true,
    type: 'number',
    sortable: true,
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'thuongXuyen3',
    headerName: '3',
    width: 40,
    editable: true,
    type: 'number',
    sortable: true,
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'thuongXuyen4',
    headerName: '4',
    width: 40,
    editable: true,
    type: 'number',
    sortable: true,
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'thuongXuyen5',
    headerName: '5',
    width: 40,
    editable: true,
    type: 'number',
    sortable: true,
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'tieuLuan_BTL',
    headerName: 'TL/BTL (%)',
    width: 120,
    editable: true,
    type: 'number',
    sortable: true,
  },
]);

export const quyUocCotDiemColumnGroupingModel = [
  {
    groupId: 'Thường xuyên',
    headerAlign: 'center' as GridAlignment,
    children: [
      { field: 'thuongXuyen1' },
      { field: 'thuongXuyen2' },
      { field: 'thuongXuyen3' },
      { field: 'thuongXuyen4' },
      { field: 'thuongXuyen5' },
    ],
  },
];
