import { GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';

export const danhMucNganhDaoTaoColumns: GridColDef[] = generateTableConfigs([
  {
    field: 'maNganh',
    headerName: 'Mã ngành',
    minWidth: 140,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenNganh',
    headerName: 'Tên ngành',
    minWidth: 220,
    flex: 1.5,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenVietTat',
    headerName: 'Tên viết tắt',
    minWidth: 140,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenTiengAnh',
    headerName: 'Tên tiếng anh',
    minWidth: 200,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'maTuyenSinh',
    headerName: 'Mã tuyển sinh',
    minWidth: 160,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'khoa',
    headerName: 'Khoa',
    minWidth: 200,
    flex: 1,
    valueGetter: (_, row) => row.khoa?.tenKhoa,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'khoiThi',
    headerName: 'Khối thi',
    minWidth: 120,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'kyTuMaSV',
    headerName: 'Ký tự Mã SV',
    minWidth: 140,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'khoiNganh',
    headerName: 'Khối ngành',
    minWidth: 140,
    flex: 1,
    valueGetter: (_, row) => row.khoiNganh?.tenKhoiNganh,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'stt',
    headerName: 'STT',
    minWidth: 80,
    flex: 0.4,
    type: 'number',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    minWidth: 160,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
  },
]);
