import { GridColDef } from '@mui/x-data-grid';

export const dangKyGiaHanNopHocPhiColumns: GridColDef[] = [
  {
    field: 'index',
    headerName: '*',
    width: 50,
    sortable: true,
    align: 'center' as const,
    headerAlign: 'center' as const,
  },
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    flex: 1,
    minWidth: 120,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    flex: 1,
    minWidth: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'lopHoc',
    headerName: 'Lớp học',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayTiepNhan',
    headerName: 'Ngày tiếp nhận',
    flex: 1,
    minWidth: 140,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'nguoiTiepNhan',
    headerName: 'Người tiếp nhận',
    flex: 1,
    minWidth: 160,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayHetHan',
    headerName: 'Ngày hết hạn',
    flex: 1,
    minWidth: 140,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'dot',
    headerName: 'Đợt',
    flex: 1,
    minWidth: 120,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'duyet',
    headerName: 'Duyệt',
    flex: 1,
    minWidth: 100,
    type: 'boolean',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
];

