import { GridColDef } from '@mui/x-data-grid';
import { format } from 'date-fns';

export const columns: GridColDef[] = [
  {
    field: 'index',
    headerName: '*',
    width: 50,
    sortable: true,
    align: 'center' as const,
    headerAlign: 'center' as const,
  },
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    width: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    flex: 1,
    minWidth: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    flex: 1,
    minWidth: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    flex: 1,
    minWidth: 100,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value) => (value ? new Date(value as string) : null),
  },
  {
    field: 'noiSinh',
    headerName: 'Nơi sinh',
    flex: 1,
    minWidth: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (_, row) =>
      `${row?.noiSinhPhuongXa?.tenPhuongXa ?? ''} ${row?.noiSinhHuyen?.tenQuanHuyen ?? ''} ${row?.noiSinhTinh?.tenTinhThanh ?? ''}`,
  },
  {
    field: 'khoa',
    headerName: 'Khoa',
    flex: 1,
    minWidth: 200,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (_, row) => row?.nganh?.khoa?.tenKhoa ?? '',
  },
  {
    field: 'nganh',
    headerName: 'Ngành',
    flex: 1,
    minWidth: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenNganhHoc ?? '',
  },
  {
    field: 'lopHoc',
    headerName: 'Lớp học',
    flex: 1,
    minWidth: 160,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenLop ?? '',
  },
  {
    field: 'coHinh',
    headerName: 'Có hình',
    width: 110,
    type: 'boolean',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (_value, row) => !!row?.hinhTheSinhVienUrl,
  },
  {
    field: 'ngayImportAnhTheSv',
    headerName: 'Ngày import hình',
    width: 140,
    sortable: true,
    filterable: false,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value) => (value ? format(value, 'dd/MM/yyyy') : null),
  },
];
