import { GridColDef } from '@mui/x-data-grid';
import { format } from 'date-fns';

export const columns: GridColDef[] = [
  {
    field: 'index',
    headerName: '*',
    width: 50,
    sortable: true,
    align: 'center' as const,
    headerAlign: 'center' as const,
  },
  {
    field: 'maHoSo',
    headerName: 'Mã hồ sơ',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soBaoDanh',
    headerName: 'Số báo danh',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'thuTuNhanHoSo',
    headerName: 'Thứ tự nhận hồ sơ',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'maBarcode',
    headerName: 'Mã barcode',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'gioiTinh',
    headerName: 'Giới tính',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: Date) => (value ? format(value, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'donViCuDiHoc',
    headerName: 'Đơn vị cử đi học',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'danToc',
    headerName: 'Dân tộc',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenDanToc,
  },
  {
    field: 'tonGiao',
    headerName: 'Tôn giáo',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenTonGiao,
  },
  {
    field: 'hoKhauThuongTru',
    headerName: 'Hộ khẩu thường trú',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoKhauTamTru',
    headerName: 'Hộ khẩu tạm trú',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'diaChiLienLac',
    headerName: 'Địa chỉ liên lạc',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenTinh',
    headerName: 'Tên tỉnh',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenTinhThanh,
  },
  {
    field: 'tenHuyen',
    headerName: 'Tên huyện',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenQuanHuyen,
  },
  {
    field: 'tenPhuongXa',
    headerName: 'Tên phường xã',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'noiSinhTinh',
    headerName: 'Nơi sinh Tỉnh',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenTinhThanh,
  },
  {
    field: 'noiSinhHuyen',
    headerName: 'Nơi sinh Huyện',
    valueGetter: (value: any) => value?.tenQuanHuyen,
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'noiSinhPhuongXa',
    headerName: 'Nơi sinh Phường xã',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'lopHoc',
    headerName: 'Lớp học',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenLop,
  },
  {
    field: 'loaiSinhVien',
    headerName: 'Loại sinh viên',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenLoaiSinhVien,
  },
  {
    field: 'nguyenQuan',
    headerName: 'Nguyên quán',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'doiTuongUuTien',
    headerName: 'Tên đối tượng',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenDoiTuong,
  },
  {
    field: 'doiTuongChinhSach',
    headerName: 'Tên đối tượng chính sách',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => (value ? `NHOM${value}` : ''),
  },
  {
    field: 'khuVuc',
    headerName: 'Khu vực',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'phanHe',
    headerName: 'Phân hệ',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'truongTotNghiep',
    headerName: 'Trường tốt nghiệp',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayVaoDoan',
    headerName: 'Ngày vào đoàn',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: Date) => (value ? format(value, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'ngayVaoDang',
    headerName: 'Ngày vào đảng',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: Date) => (value ? format(value, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'soCMND',
    headerName: 'Số CMND',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayCap',
    headerName: 'Ngày cấp',
    width: 180,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: Date) => (value ? format(value, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'noiCapCMND',
    headerName: 'Nơi cấp CMND',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'noiCap',
    headerName: 'Nơi cấp',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'coSoDaoTao',
    headerName: 'Cơ sở',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenCoSo,
  },
  {
    field: 'khoaHoc',
    headerName: 'Khóa học',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenKhoaHoc,
  },
  {
    field: 'bacDaoTao',
    headerName: 'Bậc đào tạo',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenBacDaoTao,
  },
  {
    field: 'loaiDaoTao',
    headerName: 'Loại đào tạo',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenLoaiDaoTao,
  },
  {
    field: 'nganh',
    headerName: 'Ngành',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenNganhHoc,
  },
  {
    field: 'chuyenNganh',
    headerName: 'Chuyên Ngành',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenChuyenNganh,
  },
  {
    field: 'nganh2',
    headerName: 'Ngành 2',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenNganhHoc,
  },
  {
    field: 'ngayNhapHoc',
    headerName: 'Ngày nhập học',
    width: 180,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: Date) => (value ? format(value, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'hoTenCha',
    headerName: 'Họ tên cha',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngheNghiepCha',
    headerName: 'Nghề nghiệp',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoTenMe',
    headerName: 'Họ tên mẹ',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngheNghiepMe',
    headerName: 'Nghề nghiệp',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soDienThoai',
    headerName: 'Điện thoại',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soDienThoaiPhuHuynh',
    headerName: 'Điện thoại phụ huynh',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soDienThoai2',
    headerName: 'Điện thoại 2',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soDienThoai3',
    headerName: 'Điện thoại 3',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'email',
    headerName: 'Email',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'emailTruong',
    headerName: 'Mail trường',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soTaiKhoan',
    headerName: 'Số tài khoản',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'tenNganHang',
    headerName: 'Tên ngân hàng',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'chiNhanhNganHang',
    headerName: 'Chi nhánh ngân hàng',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'maBHXHBHYT',
    headerName: 'Mã BHXH/BHYT',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'trangThai',
    headerName: 'Trạng thái',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'quocTich',
    headerName: 'Quốc tịch',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: any) => value?.tenQuocGia,
  },
  {
    field: 'truongLop12',
    headerName: 'Trường lớp 12',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'soQuyetDinh',
    headerName: 'Số quyết định',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayQuyetDinh',
    headerName: 'Ngày ra quyết định',
    width: 180,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: Date) => (value ? format(value, 'dd/MM/yyyy') : ''),
  },
  {
    field: 'dotRaQuyetDinh',
    headerName: 'Đợt ra quyết định',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'chucVu',
    headerName: 'Chức vụ',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'donViCongTac',
    headerName: 'Đơn vị công tác',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    width: 180,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
];
