export const chuongTrinhKhungTinChiRows = [
  {
    id: 1,
    tinhTrang: 'Đang học',
    maMonHoc: 'MTH101',
    tenMonHoc: 'Toán cao cấp 1',
    maHocPhan: 'HP001',
    maTuQuan: 'TQ001',
    dvht: 3,
    lt: 2,
    th: 1,
    tuHoc: 1,
    soTc: 3,
    tongSoTiet: 45,
    soTietLT: 30,
    soTietTH: 15,
    soTietTuHoc: 15,
  },
  {
    id: 2,
    tinhTrang: 'Hoàn thành',
    maMonHoc: 'PHY201',
    tenMonHoc: 'Vật lý đại cương',
    maHocPhan: 'HP002',
    maTuQuan: 'TQ002',
    dvht: 4,
    lt: 3,
    th: 1,
    tuHoc: 1,
    soTc: 4,
    tongSoTiet: 60,
    soTietLT: 45,
    soTietTH: 15,
    soTietTuHoc: 20,
  },
  {
    id: 3,
    tinhTrang: 'Đang học',
    maMonHoc: 'ENG301',
    tenMonHoc: 'Tiếng Anh học thuật',
    maHocPhan: 'HP003',
    maTuQuan: 'TQ003',
    dvht: 2,
    lt: 2,
    th: 0,
    tuHoc: 1,
    soTc: 2,
    tongSoTiet: 30,
    soTietLT: 30,
    soTietTH: 0,
    soTietTuHoc: 10,
  },
  {
    id: 4,
    tinhTrang: 'Bảo lưu',
    maMonHoc: 'CHE401',
    tenMonHoc: 'Hóa học hữu cơ',
    maHocPhan: 'HP004',
    maTuQuan: 'TQ004',
    dvht: 3,
    lt: 2,
    th: 1,
    tuHoc: 1,
    soTc: 3,
    tongSoTiet: 50,
    soTietLT: 35,
    soTietTH: 15,
    soTietTuHoc: 12,
  },
  {
    id: 5,
    tinhTrang: 'Hoàn thành',
    maMonHoc: 'CSE501',
    tenMonHoc: 'Cấu trúc dữ liệu',
    maHocPhan: 'HP005',
    maTuQuan: 'TQ005',
    dvht: 3,
    lt: 2,
    th: 1,
    tuHoc: 1,
    soTc: 3,
    tongSoTiet: 45,
    soTietLT: 30,
    soTietTH: 15,
    soTietTuHoc: 15,
  },
];
