import type { GridAlignment, GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { TRANG_THAI_SV_MAP } from '@renderer/shared/constants';
import { dateCellFormat } from '@renderer/shared/utils/date';

export const thongTinChungColumns = generateTableConfigs([
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.maSinhVien ?? '',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.hoDem ?? '',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.ten ?? '',
  },
  {
    field: 'gioiTinh',
    headerName: 'Giới tính',
    minWidth: 110,
    flex: 0.8,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => (row.gioiTinh == 0 ? 'Nữ' : 'Nam'),
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => dateCellFormat(row.ngaySinh),
  },
  {
    field: 'soDienThoai',
    headerName: 'Số điện thoại',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.soDienThoai ?? '',
  },
  {
    field: 'noiSinh',
    headerName: 'Nơi sinh',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) =>
      `${row.noiSinhPhuongXa ?? ''} ${row.noiSinhHuyen ?? ''} ${row.noiSinhTinh ?? ''}`,
  },
  {
    field: 'lopHoc',
    headerName: 'Lớp học',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.lopHoc?.tenLop || '',
  },
  {
    field: 'trangThai',
    headerName: 'Trạng thái',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => TRANG_THAI_SV_MAP[row.trangThai] ?? '',
  },
]) as GridColDef[];

export const capNhatTrangThaiSinhVienColumns = generateTableConfigs([
  {
    field: 'lopHoc',
    headerName: 'Lớp học',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.sinhVien?.lopHoc?.tenLopHoc || row.sinhVien?.lopHoc || '',
  },
  {
    field: 'trangThai',
    headerName: 'Trạng thái',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => TRANG_THAI_SV_MAP[row.trangThaiMoi] ?? '',
  },
  {
    field: 'soQuyetDinh',
    headerName: 'Số quyết định',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ngayHieuLuc',
    headerName: 'Ngày hiệu lực',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => (row.ngayQuyetDinh ? dateCellFormat(row.ngayQuyetDinh) : ''),
  },
  {
    field: 'ngayRaQuyetDinh',
    headerName: 'Ngày ra QĐ',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) =>
      row.quyetDinh?.ngayQuyetDinh ? dateCellFormat(row.quyetDinh?.ngayQuyetDinh) : '',
  },
]) as GridColDef[];
