import { GridAlignment } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';

export const phanMonChoLopHocColumns = generateTableConfigs([
  {
    field: 'tinhTrang',
    headerName: 'Tình trạng',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maMonHoc',
    headerName: 'Mã môn học',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tenMonHoc',
    headerName: 'Tên môn học',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maHocPhan',
    headerName: 'Mã học phần',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'dvht',
    headerName: 'ĐVHT',
    minWidth: 100,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'lt',
    headerName: 'LT',
    minWidth: 80,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'th',
    headerName: 'TH',
    minWidth: 80,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tuHoc',
    headerName: 'Tự học',
    minWidth: 100,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTc',
    headerName: 'Số TC',
    minWidth: 100,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tongSoTiet',
    headerName: 'Tổng số tiết',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietLT',
    headerName: 'Số tiết LT',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietTH',
    headerName: 'Số tiết TH',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietTuHoc',
    headerName: 'Số tiết tự học',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
]);
