import { GridAlignment, GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';
import { parseDonViTinh } from '@renderer/shared/enums/donViTinh.enum';
import { LoaiKhoanThu } from '@renderer/shared/types/loai-khoan-thu.types';

export const DanhMucKhoanThuTuDoColumns: GridColDef[] = generateTableConfigs([
  {
    field: 'maKhoanThu',
    headerName: 'Mã khoản thu',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
  },
  {
    field: 'tenKhoanThu',
    headerName: 'Tên khoản thu',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
  },
  {
    field: 'soTien',
    headerName: 'Số tiền',
    type: 'number',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
  },
  {
    field: 'stt',
    headerName: 'STT',
    type: 'number',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    width: 80,
  },
  {
    field: 'loaiKhoanThu',
    headerName: 'Loại khoản thu',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
    valueGetter: (value: LoaiKhoanThu) => value?.tenLoaiKhoanThu || '',
  },
  {
    field: 'thueVAT',
    headerName: 'Thuế VAT',
    type: 'number',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
  },
  {
    field: 'gomThueVAT',
    headerName: 'Gồm VAT',
    type: 'boolean',
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    width: 120,
  },
  {
    field: 'isVisible',
    headerName: 'Hiển thị',
    type: 'boolean',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
    width: 120,
  },
  {
    field: 'donViTinh',
    headerName: 'Đơn vị tính',
    sortable: true, 
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
    valueGetter: parseDonViTinh,
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    sortable: true,
    minWidth: 150,
    headerAlign: 'center' as GridAlignment,
    flex: 1,
  },
]);
