import { GridColDef } from '@mui/x-data-grid';

export const huyLopHocPhanColumns: GridColDef[] = [
  {
    field: 'index',
    headerName: '*',
    width: 50,
    sortable: true,
    align: 'center' as const,
    headerAlign: 'center' as const,
  },
  {
    field: 'maSinhVien',
    headerName: 'Mã sinh viên',
    flex: 1,
    minWidth: 120,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'hoDem',
    headerName: 'Họ đệm',
    flex: 1,
    minWidth: 140,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ten',
    headerName: 'Tên',
    flex: 1,
    minWidth: 100,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'gioiTinh',
    headerName: 'Giới tính',
    width: 110,
    type: 'singleSelect',
    valueOptions: ['Nam', 'Nữ', 'Khác'],
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngaySinh',
    headerName: 'Ngày sinh',
    flex: 1,
    minWidth: 130,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'nguoiDangKy',
    headerName: 'Người đăng ký',
    flex: 1,
    minWidth: 160,
    type: 'string',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayDangKy',
    headerName: 'Ngày đăng ký',
    flex: 1,
    minWidth: 140,
    type: 'date',
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'trangThaiDangKy',
    headerName: 'Trạng thái đăng ký',
    flex: 1,
    minWidth: 180,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'daCoDiem',
    headerName: 'Đã có điểm',
    width: 120,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'daDongHocPhi',
    headerName: 'Đã đóng học phí',
    width: 140,
    align: 'center',
    headerAlign: 'center',
  },
  {
    field: 'ngayDongHocPhi',
    headerName: 'Ngày đóng học phí',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
  },
];
