import { QuyCheHocVu } from './quy-che-hoc-vu.types';

export interface QuyCheNienChe {
  id?: string;
  idQuyCheHocVu: string;
  quyCheHocVu?: QuyCheHocVu | null;
  heSoDiemLT?: number | null;
  heSoDiemTH?: number | null;
  isTinhTheoDiemLT: boolean;
  isCotDiemKTTK: boolean;
  cotDiemKTTK?: number | null;
  isRangBuocDiemTK: boolean;
  dddS_DiemThuongKy?: number | null;
  dddS_DiemTBMon?: number | null;
  dddS_DiemThiTotNghiep?: number | null;
  dddS_DiemTBTK?: number | null;
  dddS_DiemTBHK?: number | null;
  dddS_DiemTBTN?: number | null;
  dddS_DiemKTMon?: number | null;
  dddS_DiemTBChung?: number | null;
  dddS_DiemToanKhoa?: number | null;
  dkdT_IsDaDongHP: boolean;
  dkdT_IsDTBThuongKy: boolean;
  dkdT_DTBThuongKy?: number | null;
  dkdT_IsKhongVangQua: boolean;
  dkdT_PTTongVang?: number | null;
  dkdT_PTLyThuyet?: number | null;
  dkdT_PTThucHanh?: number | null;
  dktH_DiemThoiHocMoiHK?: number | null;
  dktH_SoDVHTKhongDatHK?: number | null;
  dktH_DiemTLNam2?: number | null;
  dktH_SoDVHTKhongDatN2?: number | null;
  dktH_DiemTLNam3?: number | null;
  dktH_SoDVHTKhongDatN3?: number | null;
  dktH_IsXetHanhKiem: boolean;
  dktH_SoNamXetHanhKiem?: number | null;
  dktH_IsAutoCheckDongHP: boolean;
  hB_DiemTB?: number | null;
  hB_DiemHK?: number | null;
  hB_DiemTBToiThieu?: number | null;
  dH_DiemTB?: number | null;
  dH_DiemHanhKiem?: number | null;
  dkhT_DTBHocKy?: number | null;
  dkhT_SoDVHTKhongDatHK?: number | null;
  dkhT_DTBNam?: number | null;
  dkhT_SoDVHTKhongDatN?: number | null;
  dkhT_DiemTichLuyN2?: number | null;
  dkhT_SoDVHTKhongDatN2?: number | null;
  dkhT_DiemTichLuyN3?: number | null;
  dkhT_SoDVHTKhongDatN3?: number | null;
}
