import { LopHoc } from './lop-hoc.types';
import { CoSoTaoDao } from '@renderer/shared/types/co-so-dao-tao.types';
import { KhoaHoc } from '@renderer/shared/types/khoa-hoc.types';
import { BacDaoTao } from '@renderer/shared/types/bac-dao-tao.types';
import { LoaiDaoTao } from '@renderer/shared/types/loai-dao-tao.types';
import { NganhHoc } from '@renderer/shared/types/nganh-hoc.types';
import { ChuyenNganh } from '@renderer/features/danh-muc/chuyen-nganh';

export interface SinhVien {
  id?: string;
  maHoSo?: string;
  soBaoDanh?: string;
  thuTuNhanHoSo?: number | null;
  maSinhVien?: string;
  maBarcode?: string;
  hoDem?: string;
  ten?: string;
  gioiTinh?: number;
  ngaySinh?: string | null;
  donViCuDiHoc?: string;
  danToc?: string;
  tonGiao?: string;
  hoKhauThuongTru?: string;
  diaChiLienLac?: string;
  tenTinh?: string;
  tenHuyen?: string;
  tenPhuongXa?: string;
  noiSinhTinh?: string;
  noiSinhHuyen?: string;
  noiSinhPhuongXa?: string;
  idLopHoc?: string | null;
  idLopNienChe?: string | null;
  loaiSinhVien?: string;
  nguyenQuan?: string;
  tenDoiTuong?: string;
  tenDoiTuongChinhSach?: string;
  khuVuc?: string;
  phanHe?: string;
  truongTotNghiep?: string;
  ngayVaoDoan?: string | null;
  ngayVaoDang?: string | null;
  soCMND?: string;
  ngayCap?: string | null;
  noiCapCMND?: string;
  noiCap?: string;
  idCoSo?: string;
  coSoDaoTao?: CoSoTaoDao;
  idKhoaHoc?: string;
  khoaHoc?: KhoaHoc;
  idBacDaoTao?: string | null;
  bacDaoTao?: BacDaoTao;
  idLoaiDaoTao?: string | null;
  loaiDaoTao?: LoaiDaoTao;
  idNganh?: string | null;
  nganh?: NganhHoc;
  idChuyenNganh?: string | null;
  chuyenNganh?: ChuyenNganh;
  idNganh2?: string | null;
  ngayNhapHoc?: string | null;
  hoTenCha?: string;
  ngheNghiepCha?: string;
  hoTenMe?: string;
  ngheNghiepMe?: string;
  soDienThoai?: string;
  soDienThoaiPhuHuynh?: string;
  soDienThoai2?: string;
  soDienThoai3?: string;
  email?: string;
  emailTruong?: string;
  soTaiKhoan?: string;
  tenTaiKhoan?: string;
  tenNganHang?: string;
  chiNhanhNganHang?: string;
  maBHXHBHYT?: string;
  trangThai?: number;
  quocTich?: string;
  truongLop12?: string;
  soQuyetDinh?: string;
  ngayQuyetDinh?: string | null;
  dotRaQuyetDinh?: string;
  chucVu?: string;
  donViCongTac?: string;
  ghiChu?: string;
  hinhTheSinhVienUrl?: string;
  ngayImportAnhTheSv?: string | null;
  ngayCapNhatAnhThe?: string | null;
  anhCMNDMatTruoc?: string;
  anhCMNDMatSau?: string;
  anhBangTotNghiep?: string;
  anhHocBa?: string;
  anhGiayKhaiSinh?: string;
  anhHoKhau?: string;
  anhCMTQuanSu?: string;
  anhGiayUuTien?: string;
  anhKhac?: string;
  hoSoDaXacThuc?: boolean;
  ngayXacThucHoSo?: string | null;
  idNguoiXacThuc?: string | null;
  ghiChuHoSo?: string;
  idNguoiTao?: string | null;
  ngayTao?: string | null;
  idNguoiCapNhap?: string | null;
  ngayCapNhat?: string | null;
  isDeleted?: boolean;
  lopHoc?: LopHoc;
  anhSinhVienUrl?: string;
  fullName?: string;
}
