import { GridAlignment } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';

export const lapChuongTrinhKhungTinChiColumns = generateTableConfigs([
  {
    field: 'tinhTrang',
    headerName: 'Tình trạng',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maMonHoc',
    headerName: 'Mã môn học',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.monHoc?.maMonHoc || '',
  },
  {
    field: 'tenMonHoc',
    headerName: 'Tên môn học',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.monHoc?.tenMonHoc || '',
  },
  {
    field: 'maTuQuan',
    headerName: 'Mã tự quản',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    valueGetter: (_, row: any) => row.monHoc?.maTuQuan || '',
  },
  {
    field: 'lyThuyet',
    headerName: 'LT',
    minWidth: 80,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'thucHanh',
    headerName: 'TH',
    minWidth: 80,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tuHoc',
    headerName: 'Tự học',
    minWidth: 100,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTinChi',
    headerName: 'Số TC',
    minWidth: 100,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tongSoTiet',
    headerName: 'Tổng số tiết',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietLyThuyet',
    headerName: 'Số tiết LT',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietThucHanh',
    headerName: 'Số tiết TH',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietTuHoc',
    headerName: 'Số tiết tự học',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
]);

export const lapChuongTrinhKhungTinChiSideTableColumns = [
  {
    field: 'hocKy',
    headerName: 'Học kỳ',
    minWidth: 20,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    editable: false,
  },
  {
    field: 'soTinChiBatBuoc',
    headerName: 'Số TC bắt buộc',
    minWidth: 20,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    editable: false,
  },
  {
    field: 'soTinChiTuChon',
    headerName: 'Số TC tự chọn',
    minWidth: 20,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    editable: false,
  },
];
