import { GridAlignment, GridColDef } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';

export const tieuChuanXetDanhHieuColumns: GridColDef[] = generateTableConfigs([
  {
    field: 'stt',
    headerName: 'STT',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLuc10Tu',
    headerName: 'Học lực 10 từ',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLuc10Den',
    headerName: 'Học lực 10 đến',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLuc4Tu',
    headerName: 'Học lực 4 từ',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hocLuc4Den',
    headerName: 'Học lực 4 đến',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hanhKiemTu',
    headerName: 'Hạnh kiểm từ',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'hanhKiemDen',
    headerName: 'Hạnh kiểm đến',
    minWidth: 150,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'nhomDanhHieu',
    headerName: 'Nhóm danh hiệu',
    minWidth: 160,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
  {
    field: 'ghiChu',
    headerName: 'Ghi chú',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
    align: 'center',
  },
]);
