import { GridAlignment } from '@mui/x-data-grid';
import { generateTableConfigs } from '@renderer/shared/configs/base-table.config';

export const quanLyLopHocPhanColumns = generateTableConfigs([
  {
    field: 'maLhp',
    headerName: 'Mã LHP',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maHp',
    headerName: 'Mã HP',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'tenMonHoc',
    headerName: 'Tên môn học',
    minWidth: 180,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'maTuQuan',
    headerName: 'Mã tự quản',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTc',
    headerName: 'Số TC',
    minWidth: 100,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'ltTh',
    headerName: 'LT/TH',
    minWidth: 100,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietLt',
    headerName: 'Số tiết LT',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'soTietTh',
    headerName: 'Số tiết TH',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'siSoToiThieu',
    headerName: 'Sĩ số tối thiểu',
    minWidth: 140,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'siSoToiDa',
    headerName: 'Sĩ số tối đa',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'siSoDangKy',
    headerName: 'Sĩ số đăng ký',
    minWidth: 130,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'loaiLop',
    headerName: 'Loại lớp',
    minWidth: 110,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'trangThai',
    headerName: 'Trạng thái',
    minWidth: 120,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
  {
    field: 'lopDuKien',
    headerName: 'Lớp dự kiến',
    minWidth: 130,
    flex: 1,
    sortable: true,
    headerAlign: 'center' as GridAlignment,
  },
]);
